---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: translator-deployment
  labels:
    app: translator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: translator
  template:
    metadata:
      labels:
        app: translator
    spec:
      containers:
        - name: translator
          image: syhazard/translator:with-logging
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "2"
              memory: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: translator-service
spec:
  selector:
    app: translator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80